-- MySQL Script generated by MySQL Workbench
-- Thu Mar 13 14:57:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taskhive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taskhive` DEFAULT CHARACTER SET utf8;
USE `taskhive`;

-- -----------------------------------------------------
-- Table `proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `creador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `clave` VARCHAR(255) NOT NULL,
  `ultima_sesion` DATETIME NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProyecto` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  `estimacion` INT NULL,
  `prioridad` INT NOT NULL,
  `creador` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_task_proyecto` (`idProyecto` ASC),
  CONSTRAINT `fk_task_proyecto`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `proyecto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProyecto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_chat_proyecto` (`idProyecto` ASC),
  CONSTRAINT `fk_chat_proyecto`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `proyecto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_usuario` (
  `idUsuario` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`, `idProyecto`),
  CONSTRAINT `fk_proyecto_usuario_proyecto`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `proyecto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_proyecto_usuario_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensaje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(200) NOT NULL,
  `idUsuario` INT NOT NULL,
  `idChat` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_mensaje_usuario` (`idUsuario` ASC),
  INDEX `idx_mensaje_chat` (`idChat` ASC),
  CONSTRAINT `fk_mensaje_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mensaje_chat`
    FOREIGN KEY (`idChat`)
    REFERENCES `chat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;